### ISSUE TITLE
UI/X design: iteration 1

### ISSUE THREAD

**Issue by pwalsh** [opentrials/trial-finder#1]
# Description

Core views for the main Trial Finder app. Prior work has been done, but we need to revisit according to style guide and current understanding of public-facing features.
# Tasks
- [ ] UI/X mocks for each view
  - [ ] TBD: the list of views for iteration 1
- [ ] Base implementation of HTML + CSS for the mocks
